## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [2]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [3]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [4]:
l2=l1.append(10)

Removing from an existing list

### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [6]:
l3=l2.remove(10)

AttributeError: 'NoneType' object has no attribute 'remove'

Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [7]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [12]:
l3=l1+l2

Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [9]:
import numpy as np

In [31]:
l3=[2,4,6,8]
avg=np.mean(l3)
avg

5.0

Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [14]:
l4=[0,1,3,3,5,5,7,9]
l5=l3+l4
l4.count(5)

2

Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [15]:
l3.sort()

In [16]:
l3.sort(reverse=True)

### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [18]:
def sum_3(a,b,c):
    sum=a+b+c
    return sum

sum_3(1,2,3)

6

### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [21]:
sum=lambda x,y,z:x+y+z
print(sum(1,2,3))

6


# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [18]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [19]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [20]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2L, 4L)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [23]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [28]:
x=np.array([9,8,7,6,5,4,3,2,1]).reshape(3,3)

In [29]:
x

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [32]:
x.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [33]:
x+1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [68]:
import numpy as np
b1=[1,4 ,9,121,144,169]
b2=[16,25,36,196,225,256] 
b3=[49,64,81,289,324,361 ]
nd6=np.matrix( [b1,b2,b3])
nd6.mean()

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [73]:
a=[1,2,3,4]
b=[5,6,7,8]

In [74]:
np.dot(a,b)

70

# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [2]:
import numpy as np
import pandas as pd

In [94]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [78]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [92]:
import pandas as pd
from pandas import Series
y=pd.Series(d1)
y

a    1
b    2
c    3
dtype: int64

You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

In [96]:
z=np.dot(series1,y)
z

14

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [98]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [112]:
df1[1:2]

a  b  c
1  2  4  7

### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]



In [117]:
df1.loc[:,'c':]

c
0  6
1  7
2  8

## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors 

In [129]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']
mtcars

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                           
Mazda RX4                      Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag              Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                    Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive            Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout      Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                          Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                    Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                      Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                        Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                        Merc 280  19.2    6  167.6  123  3.92  3.440   
Merc 280C                      Merc 280C  17.8    6  167.6  123  3.92  3.440   
Merc 450SE                    Merc 450SE  16.4    8  275.8  180  3.07  4.070   
Merc 450SL                    Merc 450SL  17.3    8  275.8  180  3.07  3.730   
Merc 450SLC                  Merc 450SLC  15.2    8  275.8  180  3.07  3.780   
Cadillac Fleetwood    Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250   
Lincoln Continental  Lincoln Continental  10.4    8  460.0  215  3.00  5.424   
Chrysler Imperial      Chrysler Imperial  14.7    8  440.0  230  3.23  5.345   
Fiat 128                        Fiat 128  32.4    4   78.7   66  4.08  2.200   
Honda Civic                  Honda Civic  30.4    4   75.7   52  4.93  1.615   
Toyota Corolla            Toyota Corolla  33.9    4   71.1   65  4.22  1.835   
Toyota Corona              Toyota Corona  21.5    4  120.1   97  3.70  2.465   
Dodge Challenger        Dodge Challenger  15.5    8  318.0  150  2.76  3.520   
AMC Javelin                  AMC Javelin  15.2    8  304.0  150  3.15  3.435   
Camaro Z28                    Camaro Z28  13.3    8  350.0  245  3.73  3.840   
Pontiac Firebird        Pontiac Firebird  19.2    8  400.0  175  3.08  3.845   
Fiat X1-9                      Fiat X1-9  27.3    4   79.0   66  4.08  1.935   
Porsche 914-2              Porsche 914-2  26.0    4  120.3   91  4.43  2.140   
Lotus Europa                Lotus Europa  30.4    4   95.1  113  3.77  1.513   
Ford Pantera L            Ford Pantera L  15.8    8  351.0  264  4.22  3.170   
Ferrari Dino                Ferrari Dino  19.7    6  145.0  175  3.62  2.770   
Maserati Bora              Maserati Bora  15.0    8  301.0  335  3.54  3.570   
Volvo 142E                    Volvo 142E  21.4    4  121.0  109  4.11  2.780   

                      qsec  vs  am  gear  carb  
name                                            
Mazda RX4            16.46   0   1     4     4  
Mazda RX4 Wag        17.02   0   1     4     4  
Datsun 710           18.61   1   1     4     1  
Hornet 4 Drive       19.44   1   0     3     1  
Hornet Sportabout    17.02   0   0     3     2  
Valiant              20.22   1   0     3     1  
Duster 360           15.84   0   0     3     4  
Merc 240D            20.00   1   0     4     2  
Merc 230             22.90   1   0     4     2  
Merc 280             18.30   1   0     4     4  
Merc 280C            18.90   1   0     4     4  
Merc 450SE           17.40   0   0     3     3  
Merc 450SL           17.60   0   0     3     3  
Merc 450SLC          18.00   0   0     3     3  
Cadillac Fleetwood   17.98   0   0     3     4  
Lincoln Continental  17.82   0   0     3     4  
Chrysler Imperial    17.42   0   0     3     4  
Fiat 128             19.47   1   1     4     1  
Honda Civic          18.52   1   1     4     2  
Toyota Corolla       19.90   1   1     4     1  
Toyota Corona        20.01   1   0     3     1  
Dodge Challenger     16.87   0   0     3     2  
AMC Javelin          17.30   0   0     3     2  
Camaro Z28           15.41   0   0     3     4  
Pontiac Firebird     17.05   0   0     3 

Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [124]:
mtcars.shape

(32, 12)

In [123]:
type(mtcars)

pandas.core.frame.DataFrame

### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [125]:
mtcars.head()

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2

In [126]:
mtcars.tail()

name   mpg  cyl   disp   hp  drat     wt  qsec  vs  \
name                                                                           
Lotus Europa      Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   
Ford Pantera L  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   
Ferrari Dino      Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   
Maserati Bora    Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   
Volvo 142E          Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   

                am  gear  carb  
name                            
Lotus Europa     1     5     2  
Ford Pantera L   1     5     4  
Ferrari Dino     1     5     6  
Maserati Bora    1     5     8  
Volvo 142E       1     4     2

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [128]:
mtcars.columns

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

In [133]:
mtcars.iloc[0:7,0:4]

name   mpg  cyl   disp
name                                                  
Mazda RX4                  Mazda RX4  21.0    6  160.0
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0
Datsun 710                Datsun 710  22.8    4  108.0
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0
Valiant                      Valiant  18.1    6  225.0
Duster 360                Duster 360  14.3    8  360.0