# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets 
Iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
features = Iris.data
labels = Iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size=0.25)
print("Shape of x_train is {}".format(x_train.shape))
print("Shape of x_test is {}".format(x_test.shape))
print("Shape of y_train is {}".format(y_train.shape))
print("Shape of y_test is {}".format(y_test.shape))

Shape of x_train is (112, 4)
Shape of x_test is (38, 4)
Shape of y_train is (112,)
Shape of y_test is (38,)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
y_train = tf.keras.utils.to_categorical(y_train,num_classes=3)
y_test1 = tf.keras.utils.to_categorical(y_test,num_classes=3)

In [8]:
y_test1

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Dense
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(Dense(6,input_dim=4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(3,activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='SGD',loss=tf.keras.losses.categorical_crossentropy,metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 30        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 28        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [13]:
model.fit(x_train,y_train,epochs = 100,validation_data=(x_test,y_test1))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 2s 17ms/sample - loss: 1.7506 - accuracy: 0.3125 - val_loss: 1.2777 - val_accuracy: 0.3947
Epoch 2/100
112/112 [==============================] - 0s 209us/sample - loss: 1.4223 - accuracy: 0.3125 - val_loss: 1.2139 - val_accuracy: 0.3947
Epoch 3/100
112/112 [==============================] - 0s 198us/sample - loss: 1.2596 - accuracy: 0.3036 - val_loss: 1.1362 - val_accuracy: 0.0526
Epoch 4/100
112/112 [==============================] - 0s 208us/sample - loss: 1.1378 - accuracy: 0.1071 - val_loss: 1.0911 - val_accuracy: 0.5526
Epoch 5/100
112/112 [==============================] - 0s 207us/sample - loss: 1.0533 - accuracy: 0.6339 - val_loss: 1.0190 - val_accuracy: 0.5789
Epoch 6/100
112/112 [==============================] - 0s 212us/sample - loss: 0.9801 - accuracy: 0.6875 - val_loss: 0.9939 - val_accuracy: 0.6053
Epoch 7/100
112/112 [==============================] - 0s 200us/sample - l

## Question 10

### Make predictions
- Predict labels on one row

In [14]:
y_pred = model.predict(x_test,batch_size=1)
y_pred

array([[3.52392369e-03, 3.20202947e-01, 6.76273108e-01],
       [6.94870278e-02, 7.52072752e-01, 1.78440273e-01],
       [8.40753550e-04, 1.52060807e-01, 8.47098470e-01],
       [7.86871184e-03, 4.16233420e-01, 5.75897872e-01],
       [9.04479444e-01, 9.54059213e-02, 1.14593859e-04],
       [7.84817338e-02, 7.83185184e-01, 1.38333097e-01],
       [9.36719835e-01, 6.32436946e-02, 3.65510277e-05],
       [9.66370940e-01, 3.36181037e-02, 1.09683660e-05],
       [3.51882307e-03, 2.79780149e-01, 7.16700971e-01],
       [9.41305757e-01, 5.86483851e-02, 4.59111980e-05],
       [9.65133369e-01, 3.48572023e-02, 9.42878887e-06],
       [3.93735841e-02, 6.40235901e-01, 3.20390552e-01],
       [1.34656311e-03, 2.06527188e-01, 7.92126298e-01],
       [9.21564579e-01, 7.83006400e-02, 1.34806280e-04],
       [4.22176830e-02, 6.17269158e-01, 3.40513140e-01],
       [6.68376312e-02, 6.76521063e-01, 2.56641328e-01],
       [1.37879342e-01, 7.11441696e-01, 1.50679007e-01],
       [2.22924122e-04, 1.21291

In [16]:
import numpy as np
out = []
for val in y_pred:
  out.append(np.argmax(val))
print(out)

[2, 1, 2, 2, 0, 1, 0, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 2, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 1, 2, 1]


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [66]:
from sklearn.metrics import accuracy_score,classification_report
import numpy as np
acc = accuracy_score(y_test,out)
report=classification_report(y_test,out)
print("This is the obtained accuracy {}%".format(acc*100))
print("This is the report with the detailed scoring of F1 scores,precision & accuracy:-")
print(report)

This is the obtained accuracy 97.36842105263158%
This is the report with the detailed scoring of F1 scores,precision & accuracy:-
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.93      0.97        15
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [19]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [24]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [25]:
import pandas as pd
Prices = pd.read_csv('prices.csv')
Prices.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
Prices.drop(columns=['date','symbol'],inplace=True)

In [27]:
Prices.head(2)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [28]:
prices = Prices.iloc[:1000,:]
prices

open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
..          ...         ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
features = prices.iloc[:,:-1]
label = prices.iloc[:,4:5]

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
import numpy as np
features = np.array(features).astype('float32')
labels = np.array(label).astype('float32')

In [31]:
print("The datatype of features is now --> {}".format(features.dtype))
print("The datatype of label is now --> {}".format(labels.dtype))

The datatype of features is now --> float32
The datatype of label is now --> float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
feature_tensor = tf.convert_to_tensor(features)
featured = tf.math.l2_normalize(features)

In [33]:
featured

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202893, 0.02245905, 0.02182904, 0.02253223],
       [0.02235197, 0.0214132 , 0.02140606, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051191, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.00799559, 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

In [0]:
sess = tf.compat.v1.Session()
with sess.as_default():
  featured_norm = featured.numpy()

In [35]:
print("Voila!!the datatype is back from {} to the {} type..".format(type(featured),type(featured_norm)))

Voila!!the datatype is back from <class 'tensorflow.python.framework.ops.EagerTensor'> to the <class 'numpy.ndarray'> type..


## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.random.normal(shape =(4,5))
b = tf.zeros(shape=(5))

In [56]:
print("Checking the weights....\n",w,"\nHmm...It seems we've got the weights as required")
print("\nChecking the bias....\n",b,"\nSeems we've got the bias as well...\nMoving on to the next step..")

Checking the weights....
 tf.Tensor(
[[ 0.3274685  -0.8426258   0.3194337  -1.4075519  -2.3880599 ]
 [-1.0392479  -0.5573232   0.539707    1.6994323   0.28893656]
 [-1.5066116  -0.2645474  -0.59722406 -1.9171132  -0.62044144]
 [ 0.8504023  -0.40604794 -3.0258412   0.9058464   0.29855987]], shape=(4, 5), dtype=float32) 
Hmm...It seems we've got the weights as required

Checking the bias....
 tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32) 
Seems we've got the bias as well...
Moving on to the next step..


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def pred(X,w,b):
  res1 = tf.matmul(X,w)
  result = tf.add(res1,b)
  return result

In [0]:
result = pred(featured_norm,w,b)

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(prediction_result,y):
  return tf.math.reduce_mean(tf.square(prediction_result,y))

In [0]:
mse = loss(pred(featured_norm,w,b),labels)

In [61]:
mse

<tf.Tensor: shape=(), dtype=float32, numpy=0.0010078301>

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x,y,w,b,epochs,learning_rate):
  for i in range(epochs):
    print("\nEpoch {}/{}:-".format(i,epochs))
    with tf.GradientTape() as tape:
     tape.watch([w,b])
     curr_pred = pred(x,w,b)
     curr_loss = loss(curr_pred,y)
     dw1,db1 = tape.gradient(curr_loss,[w,b])
     w = w - learning_rate*dw1
     b = b - learning_rate*db1
    print("Current weights are\n{} \n& bias is {}".format(w,b))
    print("The loss at training iteration no {} is {}".format(i,loss(pred(x,w,b),y))) 
  return w,b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [63]:
w1,b1 = train(featured_norm,labels,w,b,100,0.01)


Epoch 0/100:-
Current weights are
[[ 0.32746986 -0.8426237   0.31943646 -1.4075512  -2.3880575 ]
 [-1.0392466  -0.55732113  0.5397098   1.699433    0.28893897]
 [-1.5066103  -0.26454535 -0.5972213  -1.9171125  -0.62043905]
 [ 0.85040367 -0.40604585 -3.0258384   0.90584713  0.29856232]] 
& bias is [6.4053347e-05 9.8640550e-05 1.3262770e-04 3.2729618e-05 1.1473722e-04]
The loss at training iteration no 0 is 0.0010032654972746968

Epoch 1/100:-
Current weights are
[[ 0.3274712  -0.8426216   0.31943923 -1.4075505  -2.388055  ]
 [-1.0392452  -0.55731905  0.5397126   1.6994337   0.28894138]
 [-1.506609   -0.2645433  -0.5972186  -1.9171118  -0.62043667]
 [ 0.85040504 -0.40604377 -3.0258355   0.90584785  0.29856473]] 
& bias is [1.2785022e-04 1.9688613e-04 2.6472437e-04 6.5328190e-05 2.2901504e-04]
The loss at training iteration no 1 is 0.0009987371740862727

Epoch 2/100:-
Current weights are
[[ 0.32747254 -0.84261954  0.319442   -1.4075497  -2.3880527 ]
 [-1.0392439  -0.55731696  0.5397154  

### Observe values of Weight
- Print the updated values

In [68]:
print("These are the updated weights :- \n{}".format(w1))

These are the updated weights 
[[ 0.32759002 -0.84243906  0.31968442 -1.4074892  -2.3878424 ]
 [-1.0391266  -0.5571364   0.5399579   1.699495    0.28915408]
 [-1.5064914  -0.26436245 -0.5969756  -1.9170511  -0.62022597]
 [ 0.85052484 -0.4058598  -3.0255876   0.9059096   0.29877907]]


### Observe values of Bias
- Print the updated values

In [69]:
print("These are the updated biases :- \n{}".format(b1))

These are the updated biases :- 
[0.00528684 0.00814161 0.01094685 0.00270144 0.00947019]
