### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
#Using tensorflow version 2 since 1 is supposedly going to be deprecated
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [3]:
print("Importing tensorflow...")
import tensorflow as tf

Importing tensorflow...


In [4]:
print("Checking if the selected tensorflow version is ==>> ",tf.__version__)

Checking if the selected tensorflow version is ==>>  2.1.0-rc1


#### Collect Fashion mnist data from tf.keras.datasets 

In [6]:
mnist = tf.keras.datasets.fashion_mnist
print("Getting the data from the keras module....")

Getting the data from the keras module....


In [9]:
print("Loading the data directly into train & test sets")
(x_train,y_train),(x_test,y_test) = mnist.load_data()
print("Checking the shape of train & test datasets..")
print("The shape of x_train is ==>>",x_train.shape)
print("The shape of x_test is ==>>",x_test.shape)
print("The shape of y_train is ==>>",y_train.shape)
print("The shape of y_test is ==>>",y_test.shape)

Loading the data directly into train & test sets
Checking the shape of train & test datasets..
The shape of x_train is ==>> (60000, 28, 28)
The shape of x_test is ==>> (10000, 28, 28)
The shape of y_train is ==>> (60000,)
The shape of y_test is ==>> (10000,)


In [13]:
print("Importing numpy..")
import numpy as np
print("Checking the data-range present in image which seems to be having \n{} values.".format(np.unique(x_train[0])))

Importing numpy..
Checking the data-range present in image which seems to be having 
[  0   1   2   3   4   6   7  10  12  13  15  18  23  29  35  36  40  41
  44  48  52  54  55  56  57  58  61  62  64  65  66  67  69  72  73  74
  75  77  80  82  88  92  98  99 102 106 107 109 115 117 119 121 122 123
 127 130 134 136 141 144 145 146 150 154 155 156 159 161 163 164 166 167
 168 169 170 171 172 173 175 176 177 178 179 180 181 182 183 185 186 187
 188 189 190 191 192 193 194 195 196 197 198 199 200 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 248 249 250 255] values.


In [15]:
print("Checking the values in the first image :")
x_train[0]

Checking the values in the first image :


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

#### Change train and test labels into one-hot vectors

In [20]:
print("Checking the values present in the labels..")
tf.unique(y_train)

Checking the values present in the labels..


Unique(y=<tf.Tensor: shape=(10,), dtype=uint8, numpy=array([9, 0, 3, 2, 7, 5, 1, 6, 4, 8], dtype=uint8)>, idx=<tf.Tensor: shape=(60000,), dtype=int32, numpy=array([0, 1, 1, ..., 2, 1, 5], dtype=int32)>)

In [21]:
print("Encoding the train label into one-hot vector")
y_train_enc = tf.keras.utils.to_categorical(y_train,num_classes=10)

Encoding the train label into one-hot vector


In [22]:
print("Encoding the test label into one-hot vector")
y_test_enc = tf.keras.utils.to_categorical(y_test,num_classes=10)

Encoding the test label into one-hot vector


#### Build the Graph

#### Initialize model, reshape & normalize data

In [23]:
x_train.shape

(60000, 28, 28)

In [26]:
print("Import models module from keras.. \nImporting layers module from keras..")
from tensorflow.keras import models
from tensorflow.keras import layers
print("Normalizing the data")
x_train_norm = x_train/255
x_test_norm = x_test/255
print("Reshaping the model as well as initializing the model")
model = models.Sequential([layers.Flatten(input_shape=(28,28))])

Import models module from keras.. 
Importing layers module from keras..
Normalizing the data
Reshaping the model as well as initializing the model


In [27]:
print("Checking the values")
import numpy as np
np.unique(x_train_norm)

Checking the values


array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568627,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313725, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.0745098 ,
       0.07843137, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
       0.09803922, 0.10196078, 0.10588235, 0.10980392, 0.11372549,
       0.11764706, 0.12156863, 0.1254902 , 0.12941176, 0.13333333,
       0.1372549 , 0.14117647, 0.14509804, 0.14901961, 0.15294118,
       0.15686275, 0.16078431, 0.16470588, 0.16862745, 0.17254902,
       0.17647059, 0.18039216, 0.18431373, 0.18823529, 0.19215686,
       0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
       0.21568627, 0.21960784, 0.22352941, 0.22745098, 0.23137255,
       0.23529412, 0.23921569, 0.24313725, 0.24705882, 0.25098039,
       0.25490196, 0.25882353, 0.2627451 , 0.26666667, 0.27058824,
       0.2745098 , 0.27843137, 0.28235294, 0.28627451, 0.29019

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [29]:
print("Adding dropout layer at the beginning with 2 Dense layers having 200 & 100 neurons respectively.")
model.add(layers.Dropout(0.25))
model.add(layers.Dense(200,activation = 'relu',input_shape=(28,28)))
model.add(layers.Dense(100,activation='relu'))

Adding dropout layer at the beginning with 2 Dense layers having 200 & 100 neurons respectively.


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [30]:
print("Adding the final/output layer")
model.add(layers.Dense(10,activation = 'softmax'))
print("Compiling the model as per instructed")
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics = ['accuracy'])

Adding the final/output layer
Compiling the model as per instructed


In [31]:
print("Fitting the model to check how well it's reducing the loss")
model.fit(x_train_norm,y_train_enc,epochs=50,validation_data=(x_test_norm,y_test_enc),batch_size=32)

Fitting the model to check how well it's reducing the loss
Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 8s 131us/sample - loss: 0.5837 - accuracy: 0.7864 - val_loss: 0.4386 - val_accuracy: 0.8402
Epoch 2/50
60000/60000 [==============================] - 6s 103us/sample - loss: 0.4444 - accuracy: 0.8369 - val_loss: 0.4353 - val_accuracy: 0.8285
Epoch 3/50
60000/60000 [==============================] - 6s 100us/sample - loss: 0.4096 - accuracy: 0.8509 - val_loss: 0.3997 - val_accuracy: 0.8533
Epoch 4/50
60000/60000 [==============================] - 6s 101us/sample - loss: 0.3847 - accuracy: 0.8572 - val_loss: 0.3716 - val_accuracy: 0.8611
Epoch 5/50
60000/60000 [==============================] - 6s 97us/sample - loss: 0.3710 - accuracy: 0.8630 - val_loss: 0.3718 - val_accuracy: 0.8612
Epoch 6/50
60000/60000 [==============================] - 6s 99us/sample - loss: 0.3561 - accuracy: 0.8679 - val_loss: 0.3719 - val_accuracy: 

In [32]:
print("Getting the final evaluation on train set")
eval1 = model.evaluate(x_train_norm,y_train_enc)
print("The training loss is {}% & the training accuracy is {}% ".format(eval1[0]*100,eval1[1]*100))

Getting the final evaluation on train set
60000/60000 [==============================] - 4s 65us/sample - loss: 0.1977 - accuracy: 0.9262
The training loss is 19.770803134540717% & the training accuracy is 92.61833429336548% 


In [33]:
print("Getting the final evaluation on test set")
eval2 = model.evaluate(x_test_norm,y_test_enc)
print("The test loss is {}% & the test accuracy is {}% ".format(eval2[0]*100,eval2[1]*100))

Getting the final evaluation on test set
10000/10000 [==============================] - 1s 70us/sample - loss: 0.3241 - accuracy: 0.8891
The test loss is 32.405614990592% & the test accuracy is 88.91000151634216% 
